In [1]:
import pandas as pd

In [3]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [4]:
df = pd.DataFrame(data=d)

In [6]:
df

      sales          city    size
0    100000         Tampa   Small
1    222000         Tampa  Medium
2   1000000       Orlando   Large
3    522000  Jacksonville   Large
4    111111         Miami   Small
5    222222  Jacksonville  Medium
6   1111111         Miami   Large
7     20000         Miami   Small
8     75000       Orlando  Medium
9     90000       Orlando  Medium
10  1000000       Orlando  Medium
11    10000       Orlando   Small

In [7]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [8]:
ohe = OneHotEncoder(sparse_output=False)

In [9]:
ode = OrdinalEncoder()

In [10]:
from sklearn.compose import make_column_transformer

In [11]:
ct = make_column_transformer(
  (ohe, ['city']),
  (ode, ['size']),
  remainder='passthrough'
 )

In [12]:
ct.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False), ['city']),
                                ('ordinalencoder', OrdinalEncoder(), ['size'])])

In [13]:
df_pandas=ct.fit_transform(df)

In [14]:
df_pandas

,onehotencoder__city_Jacksonville,onehotencoder__city_Miami,onehotencoder__city_Orlando,onehotencoder__city_Tampa,ordinalencoder__size,remainder__sales
0,0.0,0.0,0.0,1.0,2.0,100000
1,0.0,0.0,0.0,1.0,1.0,222000
2,0.0,0.0,1.0,0.0,0.0,1000000
3,1.0,0.0,0.0,0.0,0.0,522000
4,0.0,1.0,0.0,0.0,2.0,111111
5,1.0,0.0,0.0,0.0,1.0,222222
6,0.0,1.0,0.0,0.0,0.0,1111111
7,0.0,1.0,0.0,0.0,2.0,20000
8,0.0,0.0,1.0,0.0,1.0,75000
9,0.0,0.0,1.0,0.0,1.0,90000
10,0.0,0.0,1.0,0.0,1.0,1000000
11,0.0,0.0,1.0,0.0,2.0,10000

In [16]:
ct2 = make_column_transformer(
  (ohe, [1]),
  (ode, [2]),
  remainder='drop'
 )

In [17]:
ct2.set_output(transform='pandas')

ColumnTransformer(transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False), [1]),
                                ('ordinalencoder', OrdinalEncoder(), [2])])

In [18]:
df_pandas2 = ct2.fit_transform(df)

In [19]:
df_pandas2

,onehotencoder__city_Jacksonville,onehotencoder__city_Miami,onehotencoder__city_Orlando,onehotencoder__city_Tampa,ordinalencoder__size
0,0.0,0.0,0.0,1.0,2.0
1,0.0,0.0,0.0,1.0,1.0
2,0.0,0.0,1.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,2.0
5,1.0,0.0,0.0,0.0,1.0
6,0.0,1.0,0.0,0.0,0.0
7,0.0,1.0,0.0,0.0,2.0
8,0.0,0.0,1.0,0.0,1.0
9,0.0,0.0,1.0,0.0,1.0
10,0.0,0.0,1.0,0.0,1.0
11,0.0,0.0,1.0,0.0,2.0

In [20]:
ct3 = make_column_transformer(
  (ohe, ['city']),
  ('passthrough', ['size']),
  remainder='drop'
 )

In [21]:
ct3.set_output(transform="pandas")

ColumnTransformer(transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False), ['city']),
                                ('passthrough', 'passthrough', ['size'])])

In [22]:
df_pandas3 = ct3.fit_transform(df)

In [23]:
df_pandas3

,onehotencoder__city_Jacksonville,onehotencoder__city_Miami,onehotencoder__city_Orlando,onehotencoder__city_Tampa,passthrough__size
0,0.0,0.0,0.0,1.0,Small
1,0.0,0.0,0.0,1.0,Medium
2,0.0,0.0,1.0,0.0,Large
3,1.0,0.0,0.0,0.0,Large
4,0.0,1.0,0.0,0.0,Small
5,1.0,0.0,0.0,0.0,Medium
6,0.0,1.0,0.0,0.0,Large
7,0.0,1.0,0.0,0.0,Small
8,0.0,0.0,1.0,0.0,Medium
9,0.0,0.0,1.0,0.0,Medium
10,0.0,0.0,1.0,0.0,Medium
11,0.0,0.0,1.0,0.0,Small