In [35]:
import pandas as pd

In [36]:
df=pd.read_csv('500hits.csv', encoding='latin-1')

In [37]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [38]:
df=df.drop(columns=['PLAYER','CS'])

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YRS     465 non-null    int64
 1   G       465 non-null    int64
 2   AB      465 non-null    int64
 3   R       465 non-null    int64
 4   H       465 non-null    int64
 5   2B      465 non-null    int64
 6   3B      465 non-null    int64
 7   HR      465 non-null    int64
 8   RBI     465 non-null    int64
 9   BB      465 non-null    int64
 10  SO      465 non-null    int64
 11  SB      465 non-null    int64
 12  BA      465 non-null    float64
 13  HOF     465 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 51.0 KB

In [40]:
df.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,17.049,2048.699,7511.456,1150.314,2170.247,380.953,78.555,201.049,894.260,783.561,847.471,195.905,0.289,0.329
std,2.765,354.392,1294.066,289.635,424.191,96.483,49.363,143.623,486.193,327.432,489.224,181.846,0.021,0.475
min,11.000,1331.000,4981.000,601.000,1660.000,177.000,3.000,9.000,0.000,239.000,0.000,7.000,0.246,0.000
25%,15.000,1802.000,6523.000,936.000,1838.000,312.000,41.000,79.000,640.000,535.000,436.000,63.000,0.273,0.000
50%,17.000,1993.000,7241.000,1104.000,2076.000,366.000,67.000,178.000,968.000,736.000,825.000,137.000,0.287,0.000
75%,19.000,2247.000,8180.000,1296.000,2375.000,436.000,107.000,292.000,1206.000,955.000,1226.000,285.000,0.300,1.000
max,26.000,3308.000,12364.000,2295.000,4189.000,792.000,309.000,755.000,2297.000,2190.000,2597.000,1406.000,0.366,2.000

In [41]:
col_index = int(df.shape[1] * 0.13)
X1 = df.iloc[:, col_index]

In [42]:
col_index = int(df.shape[1] * 0.13)
X2 = df.iloc[:, col_index]

In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
scaleStandard = StandardScaler()

In [45]:
X1 = scaleStandard.fit_transform(X1)

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [ ]:
X1 = pd.DataFrame(X1, columns=['YRS','G','AB','R','H','2B','3B','HR','RBI','BB','SO'])

In [ ]:
X1.describe().round(3)

              G
count   465.000
mean   2048.699
std     354.392
min    1331.000
25%    1802.000
50%    1993.000
75%    2247.000
max    3308.000

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaleMinMax = MinMaxScaler(feature_range=(0,1))

In [ ]:
X2 = scaleMinMax.fit_transform(X2)

In [ ]:
X2 = pd.DataFrame(X2, columns = ['YRS','G','AB','R','H','2B','3B','HR','RBI','BB','SO'])

In [ ]:
X2.head()

In [ ]:
X2.describe().round(3)