In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('500hits.csv', encoding='latin-1')

In [3]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [ ]:
df2 = pd.get_dummies(df[['PLAYER', 'CS']]) #converts categorical variables into one-hot encoded column

In [5]:
df2

,CS,PLAYER_A.J. Pierzynski,PLAYER_Adam Jones,PLAYER_Al Kaline,PLAYER_Al Oliver,PLAYER_Al Simmons,PLAYER_Alan Trammell,PLAYER_Albert Belle,PLAYER_Alex Rios,PLAYER_Alfonso Soriano,...,PLAYER_Willie Horton,PLAYER_Willie Keeler,PLAYER_Willie Mays,PLAYER_Willie McCovey,PLAYER_Willie McGee,PLAYER_Willie Randolph,PLAYER_Willie Stargell,PLAYER_Willie Wilson,PLAYER_Yogi Berra,PLAYER_Zack Wheat
0,178,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,31,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,129,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,97,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,15,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,101,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
461,21,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
462,100,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
463,68,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
464,90,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
df3 = pd.concat([df,df2], axis=1)

In [7]:
df3

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,...,PLAYER_Willie Horton,PLAYER_Willie Keeler,PLAYER_Willie Mays,PLAYER_Willie McCovey,PLAYER_Willie McGee,PLAYER_Willie Randolph,PLAYER_Willie Stargell,PLAYER_Willie Wilson,PLAYER_Yogi Berra,PLAYER_Zack Wheat
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,...,False,False,False,False,False,False,False,False,False,False
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,...,False,False,False,False,False,False,False,False,False,False
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,...,False,False,False,False,False,False,False,False,False,False
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,...,False,False,False,False,False,False,False,False,False,False
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Jim Wynn,15,1920,6653,1105,1665,285,39,291,964,...,False,False,False,False,False,False,False,False,False,False
461,Jorge Posada,17,1829,6092,900,1664,379,10,275,1065,...,False,False,False,False,False,False,False,False,False,False
462,Brady Anderson,15,1834,6499,1062,1661,338,67,210,761,...,False,False,False,False,False,False,False,False,False,False
463,Cookie Rojas,16,1822,6309,714,1660,254,25,54,593,...,False,False,False,False,False,False,False,False,False,False
464,Mickey Rivers,15,1468,5629,785,1660,247,71,61,499,...,False,False,False,False,False,False,False,False,False,False

In [8]:
df4=df3.drop(['PLAYER', 'CS'], axis=1)

In [9]:
df4

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,...,PLAYER_Willie Horton,PLAYER_Willie Keeler,PLAYER_Willie Mays,PLAYER_Willie McCovey,PLAYER_Willie McGee,PLAYER_Willie Randolph,PLAYER_Willie Stargell,PLAYER_Willie Wilson,PLAYER_Yogi Berra,PLAYER_Zack Wheat
0,24,3035,11434,2246,4189,724,295,117,726,1249,...,False,False,False,False,False,False,False,False,False,False
1,22,3026,10972,1949,3630,725,177,475,1951,1599,...,False,False,False,False,False,False,False,False,False,False
2,22,2789,10195,1882,3514,792,222,117,724,1381,...,False,False,False,False,False,False,False,False,False,False
3,20,2747,11195,1923,3465,544,66,260,1311,1082,...,False,False,False,False,False,False,False,False,False,False
4,21,2792,10430,1736,3430,640,252,101,0,963,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,15,1920,6653,1105,1665,285,39,291,964,1224,...,False,False,False,False,False,False,False,False,False,False
461,17,1829,6092,900,1664,379,10,275,1065,936,...,False,False,False,False,False,False,False,False,False,False
462,15,1834,6499,1062,1661,338,67,210,761,960,...,False,False,False,False,False,False,False,False,False,False
463,16,1822,6309,714,1660,254,25,54,593,396,...,False,False,False,False,False,False,False,False,False,False
464,15,1468,5629,785,1660,247,71,61,499,266,...,False,False,False,False,False,False,False,False,False,False

In [11]:
X = df4.drop(['YRS'], axis=1)

In [12]:
y = df4['YRS']

In [14]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=10)

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
gnb = GaussianNB()

In [18]:
gnb.fit(X_train, y_train)

GaussianNB()

In [19]:
y_pred = gnb.predict(X_test)

In [20]:
from sklearn.metrics import classification_report

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          11       0.00      0.00      0.00         1
          12       0.03      1.00      0.06         1
          13       0.00      0.00      0.00         3
          14       0.00      0.00      0.00        10
          15       0.00      0.00      0.00        19
          16       0.00      0.00      0.00        11
          17       0.00      0.00      0.00         9
          18       0.00      0.00      0.00         6
          19       0.00      0.00      0.00        11
          20       0.00      0.00      0.00         8
          21       0.00      0.00      0.00         3
          22       0.00      0.00      0.00         6
          23       0.10      0.33      0.15         3
          24       0.00      0.00      0.00         1
          25       0.03      1.00      0.06         1

    accuracy                           0.03        93
   macro avg       0.01      0.16      0.02        93
weighted avg       0.00      0.03      0.01        93

c:\Users\KIIT0001\OneDrive\Desktop\mllearnings\scikitlearn\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\KIIT0001\OneDrive\Desktop\mllearnings\scikitlearn\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\KIIT0001\OneDrive\Desktop\mllearnings\scikitlearn\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [23]:
gnb.score(X_train, y_train)

1.0

In [24]:
gnb.score(X_test, y_test)

0.03225806451612903

add parameters

In [27]:
param_grid = {
    'var_smoothing': [0.01, 0.02, 0.003]
}

In [25]:
from sklearn.model_selection import GridSearchCV

In [28]:
grid_search = GridSearchCV(gnb, param_grid, cv=5, scoring='accuracy', n_jobs=-1)

In [29]:
grid_search.fit(X_train, y_train)

c:\Users\KIIT0001\OneDrive\Desktop\mllearnings\scikitlearn\.venv\Lib\site-packages\sklearn\model_selection\_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

GridSearchCV(cv=5, estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': [0.01, 0.02, 0.003]},
             scoring='accuracy')

In [30]:
grid_search.best_params_

{'var_smoothing': 0.02}

In [31]:
grid_search.best_score_

np.float64(0.20691891891891895)