In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('500hits.csv', encoding='latin-1')

In [4]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [5]:
df = df.drop(columns = ['PLAYER', 'CS'])

In [6]:
X = df.iloc[:, 0:13]

In [7]:
y = df.iloc[:, 13]

In [8]:
X

     YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB     BA
0     24  3035  11434  2246  4189  724  295  117   726  1249   357  892  0.366
1     22  3026  10972  1949  3630  725  177  475  1951  1599   696   78  0.331
2     22  2789  10195  1882  3514  792  222  117   724  1381   220  432  0.345
3     20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358  0.310
4     21  2792  10430  1736  3430  640  252  101     0   963   327  722  0.329
..   ...   ...    ...   ...   ...  ...  ...  ...   ...   ...   ...  ...    ...
460   15  1920   6653  1105  1665  285   39  291   964  1224  1427  225  0.250
461   17  1829   6092   900  1664  379   10  275  1065   936  1453   20  0.273
462   15  1834   6499  1062  1661  338   67  210   761   960  1190  315  0.256
463   16  1822   6309   714  1660  254   25   54   593   396   489   74  0.263
464   15  1468   5629   785  1660  247   71   61   499   266   471  267  0.295

[465 rows x 13 columns]

In [9]:
y

0      1
1      1
2      1
3      1
4      1
      ..
460    0
461    0
462    0
463    0
464    0
Name: HOF, Length: 465, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=17, test_size=0.2)

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
rf = RandomForestClassifier()

In [15]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred = rf.predict(X_test) #takes features from test set(X_test) and uses trained model to outpout predicted labels

In [18]:
rf.score(X_test, y_test) #for classifiers, score returns accuracy, for regressors retiurn R^2 score -> coefficient of determination

0.8279569892473119

In [19]:
from sklearn.metrics import classification_report

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.90      0.87        61
           1       0.79      0.69      0.73        32

    accuracy                           0.83        93
   macro avg       0.82      0.79      0.80        93
weighted avg       0.83      0.83      0.82        93

In [22]:
features = pd.DataFrame(rf.feature_importances_, index=X.columns)

In [24]:
features.head(15)

            0
YRS  0.036988
G    0.070032
AB   0.084690
R    0.130477
H    0.150115
2B   0.065389
3B   0.048316
HR   0.060048
RBI  0.088112
BB   0.047761
SO   0.049186
SB   0.047734
BA   0.121153

In [ ]:
rf2 = RandomForestClassifier(
    n_estimators=1000, criterion='entropy', min_samples_split=10, max_depth=14, random_state=42
) #n-estimatores -> np. of trees in the forest, more trees = more stable prediction(less variance), criterion is the metric used to measure qualty of split, entropy is info gain (gini impurity), min_sample_split is the min no. of samples reqd to split node into child nodes, larger values = simpler trees (less overfiitting), max_depth is max depth of each decision tree in forest, limits how many splits the tree can make from root to leaf, prevents overfitting by stopping tree from becoming too deep

In [26]:
rf2.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=14, min_samples_split=10,
                       n_estimators=1000, random_state=42)

In [27]:
rf2.score(X_test, y_test)

0.8494623655913979

In [28]:
y_pred2 = rf2.predict(X_test)

In [29]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.85      0.93      0.89        61
           1       0.85      0.69      0.76        32

    accuracy                           0.85        93
   macro avg       0.85      0.81      0.82        93
weighted avg       0.85      0.85      0.85        93